# Generated by Django 5.2.6 on 2026-03-25 14:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Faculty Name')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='Faculty Code')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Course Name')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Course Code')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Courses', to='User.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Project Title')),
                ('abstract', models.TextField(verbose_name='Project Abstract')),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('closed', 'Closed')], default='available', max_length=10, verbose_name='Status')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Projects', to='User.course')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Projects', to='User.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Activity Title')),
                ('description', models.TextField(verbose_name='Activity Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=1, default=0.0, max_digits=1, verbose_name='Weight / Credit Units')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activities', to='User.project')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('role', models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='student', editable=False, max_length=12)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('reg_no', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='Registration Number')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', verbose_name='Gender')),
                ('academic_year', models.IntegerField(verbose_name='Academic Year')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Students', to='User.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Students', to='User.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='data/submissions/', verbose_name='File Name')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed')], default='pending', max_length=10, verbose_name='Status')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Submissions', to='User.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Submissions', to='User.student')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('role', models.CharField(choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], default='supervisor', editable=False, max_length=12)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('reg_no', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='Registration Number')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', verbose_name='Gender')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supervisors', to='User.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supervisors', to='User.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Students', to='User.supervisor'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to='User.supervisor'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(verbose_name='Comments')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=1, verbose_name='Grade')),
                ('supervision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Feedbacks', to='User.supervision')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Feedbacks', to='User.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, null=True, unique=True, verbose_name='user Name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='supervisor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
