# Generated by Django 5.2.6 on 2026-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=' ', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(default=' ', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
