# Generated by Django 6.0.3 on 2026-03-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_student_gender_alter_supervisor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/activities/images/', verbose_name='Activity Image'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/students/profile_images/', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/supervisors/profile_images/', verbose_name='Profile Image'),
        ),
    ]
