# Generated by Django 6.0.3 on 2026-03-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_activity_image_student_image_supervisor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/images/', verbose_name='Activity Image'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students/profile_images/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supervisors/profile_images/', verbose_name='Profile Image'),
        ),
    ]
